[versions]
agp = "9.0.0"
rxandroid = "3.0.2"
rxjava = "3.1.12"
sdkBom = "1.0.14"
material = "1.13.0"
constraintlayout = "2.2.1"
navigation = "2.9.7"

[libraries]
rxandroid = { module = "io.reactivex.rxjava3:rxandroid", version.ref = "rxandroid" }
rxjava = { module = "io.reactivex.rxjava3:rxjava", version.ref = "rxjava" }
sdk-bom = { module = "com.mcards.sdk:bom", version.ref = "sdkBom" }
sdk-accounts = { module = "com.mcards.sdk:accounts" }
sdk-auth = { module = "com.mcards.sdk:auth" }
sdk-cards = { module = "com.mcards.sdk:cards" }

material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

